"""
A simple STRIPS-style planning agent.

CS F407 Artificial Intelligence -- Laboratory: Logical Reasoning for Planning
Warehouse robot: transport a package from A to C.

    Logic + Search = Planning

The LOGICAL component decides *what is possible*:  S |= Pre(a)  means a is
applicable in S, and  S' = (S minus Del(a)) union Add(a)  is the resulting
state.  The SEARCH component decides *what to try*: breadth-first search over
the reachable state space, shortest plan first.

Provenance
----------
The overall structure (Action / Problem / bfs_plan) was generated by an LLM
from the specification in `prompts.md` (Prompt 1).  Everything marked [HAND]
below was written or repaired by hand afterwards; see LAB_REPORT.md section 7.

Standard library only.  Python 3.8+.
"""

from collections import deque
from itertools import permutations


# ----------------------------------------------------------------------------
# 1. States and propositions
# ----------------------------------------------------------------------------
#
# A proposition is just a string, e.g. "At(Robot,A)".  A state is a frozenset
# of the propositions that are TRUE in it.  Anything absent is FALSE -- this is
# the closed-world assumption, and it is the single most important modelling
# choice in the file.
#
# [HAND] frozenset, not set: states are used as dictionary keys and set members
# for duplicate detection, so they must be hashable AND immutable.  The first
# generated version used a plain `set` and raised
#   TypeError: unhashable type: 'set'
# the moment duplicate detection was added.


def make_state(*propositions):
    """Build a state from a list of true propositions."""
    return frozenset(propositions)


def show_state(state):
    """Render a state in a stable, readable order."""
    return "{" + ", ".join(sorted(state)) + "}"


# ----------------------------------------------------------------------------
# 2. Actions
# ----------------------------------------------------------------------------


class Action:
    """A ground (fully instantiated) STRIPS action.

    name      : str, e.g. "Move(A,B)"
    pos_pre   : propositions that must be TRUE  for the action to apply
    neg_pre   : propositions that must be FALSE for the action to apply
    pos_eff   : propositions made TRUE  by the action   (the add list)
    neg_eff   : propositions made FALSE by the action   (the delete list)
    """

    def __init__(self, name, pos_pre=(), neg_pre=(), pos_eff=(), neg_eff=()):
        self.name = name
        self.pos_pre = frozenset(pos_pre)
        self.neg_pre = frozenset(neg_pre)
        self.pos_eff = frozenset(pos_eff)
        self.neg_eff = frozenset(neg_eff)

    # -- the logical component ------------------------------------------------

    def applicable(self, state):
        """Is  state |= Preconditions(self)  ?

        Positive preconditions must all be present; negative preconditions must
        all be absent.  Absence-means-false is the closed-world assumption.
        """
        return self.pos_pre <= state and not (self.neg_pre & state)

    def apply(self, state):
        """S' = (S minus Del) union Add.

        Delete first, then add.  The order matters whenever a proposition
        appears in both lists: add-after-delete keeps it, delete-after-add
        loses it.  The specification in `prompts.md` fixed this order
        explicitly so the generated code could not choose for itself.
        """
        return (state - self.neg_eff) | self.pos_eff

    def why_inapplicable(self, state):
        """[HAND] Explain a failure.  Used by the tests and by the report."""
        missing = sorted(self.pos_pre - state)
        forbidden = sorted(self.neg_pre & state)
        reasons = []
        if missing:
            reasons.append("missing " + ", ".join(missing))
        if forbidden:
            reasons.append("forbidden " + ", ".join(forbidden))
        return "; ".join(reasons) if reasons else "applicable"

    def __repr__(self):
        return "Action(%s)" % self.name


# ----------------------------------------------------------------------------
# 3. Problems
# ----------------------------------------------------------------------------


class Problem:
    """A planning problem (I, A, G)."""

    def __init__(self, initial, actions, goal, name="problem"):
        self.initial = frozenset(initial)
        self.actions = list(actions)
        self.goal = frozenset(goal)          # positive goal literals
        self.name = name

    def satisfies_goal(self, state):
        """[HAND] Goal test.

        This is  state |= G,  i.e. G is a SUBSET of the state -- NOT equality.
        The goal is a partial description of the world: {At(Package,C)} says
        nothing about where the robot ends up, and a state that also contains
        At(Robot,C) still satisfies it.

        The first generated version wrote `state == self.goal` and reported
        "No plan found" on a solvable problem.  See LAB_REPORT.md section 7,
        Defect 0.
        """
        return self.goal <= state

    def applicable_actions(self, state):
        return [a for a in self.actions if a.applicable(state)]


# ----------------------------------------------------------------------------
# 4. Search
# ----------------------------------------------------------------------------


class Result:
    """Outcome of a planning run."""

    def __init__(self, plan, states, expanded, generated, peak_frontier):
        self.plan = plan                  # list[Action] or None
        self.states = states              # list[frozenset]: S0 .. Sn, or None
        self.expanded = expanded
        self.generated = generated
        self.peak_frontier = peak_frontier

    @property
    def found(self):
        return self.plan is not None

    @property
    def length(self):
        return len(self.plan) if self.plan is not None else None


def bfs_plan(problem, max_expansions=200000):
    """Breadth-first search over states.  Returns a Result.

    Shortest-plan-first, because BFS explores the state space in order of
    increasing plan length and every action costs 1.

    [HAND] `visited` is essential, not an optimisation.  Move(A,B) and
    Move(B,A) form a 2-cycle, so without duplicate detection the frontier
    never empties and an unsolvable problem loops forever instead of
    reporting failure.  See LAB_REPORT.md section 7, Defect 1.
    """
    start = problem.initial

    # Goal test on pop rather than on generation, so `expanded` means the same
    # thing for every algorithm compared in experiments.py.
    frontier = deque([start])
    parent = {start: (None, None)}        # state -> (previous state, action)
    visited = {start}

    expanded = 0
    generated = 1
    peak_frontier = 1

    while frontier:
        peak_frontier = max(peak_frontier, len(frontier))
        state = frontier.popleft()
        expanded += 1

        if problem.satisfies_goal(state):
            plan, states = _reconstruct(parent, state)
            return Result(plan, states, expanded, generated, peak_frontier)

        if expanded > max_expansions:
            raise RuntimeError("expansion limit reached -- probable non-termination")

        for action in problem.actions:
            if not action.applicable(state):
                continue
            successor = action.apply(state)
            generated += 1
            if successor in visited:
                continue
            visited.add(successor)
            parent[successor] = (state, action)
            frontier.append(successor)

    return Result(None, None, expanded, generated, peak_frontier)


def bfs_plan_no_visited(problem, max_expansions=200000):
    """[HAND] The defective first version, kept so experiments.py can
    demonstrate the failure rather than merely assert it.

    Identical to bfs_plan except that the `visited` set is gone.  On a
    solvable problem it still returns a shortest plan.  On an unsolvable one
    it never terminates: Move(A,B) / Move(B,A) is a 2-cycle, so the frontier
    keeps refilling and the search never runs out of states to expand.
    """
    start = problem.initial
    frontier = deque([(start, [], [start])])
    expanded = 0
    generated = 1
    peak_frontier = 1

    while frontier:
        peak_frontier = max(peak_frontier, len(frontier))
        state, plan, states = frontier.popleft()
        expanded += 1

        if problem.satisfies_goal(state):
            return Result(plan, states, expanded, generated, peak_frontier)

        if expanded > max_expansions:
            raise RuntimeError("expansion limit reached -- probable non-termination")

        for action in problem.actions:
            if not action.applicable(state):
                continue
            successor = action.apply(state)
            generated += 1
            frontier.append((successor, plan + [action], states + [successor]))

    return Result(None, None, expanded, generated, peak_frontier)


def dfs_plan(problem, depth_limit=50, max_expansions=200000):
    """[HAND] Depth-first search, for the comparison in experiments.py.

    Present only to show what BFS buys you: DFS is complete here (the state
    space is finite and cycles on the current path are cut) but it is NOT
    optimal -- it returns the first plan it stumbles into, not the shortest.
    """
    start = problem.initial
    stack = [(start, [], [start], {start})]
    expanded = 0
    generated = 1
    peak_frontier = 1

    while stack:
        peak_frontier = max(peak_frontier, len(stack))
        state, plan, states, on_path = stack.pop()
        expanded += 1

        if problem.satisfies_goal(state):
            return Result(plan, states, expanded, generated, peak_frontier)

        if expanded > max_expansions:
            raise RuntimeError("expansion limit reached -- probable non-termination")
        if len(plan) >= depth_limit:
            continue

        # reversed() so the first action in the domain is explored first
        for action in reversed(problem.actions):
            if not action.applicable(state):
                continue
            successor = action.apply(state)
            generated += 1
            if successor in on_path:            # cut cycles on the current path
                continue
            stack.append((successor, plan + [action], states + [successor],
                          on_path | {successor}))

    return Result(None, None, expanded, generated, peak_frontier)


def _reconstruct(parent, state):
    """Walk the parent chain back to the initial state."""
    plan, states = [], [state]
    while True:
        prev, action = parent[state]
        if prev is None:
            break
        plan.append(action)
        states.append(prev)
        state = prev
    plan.reverse()
    states.reverse()
    return plan, states


# ----------------------------------------------------------------------------
# 5. Independent validation
# ----------------------------------------------------------------------------
#
# [HAND] None of this came from the LLM.  The point of the laboratory is that a
# generated plan -- and a generated *explanation* of a plan -- is not evidence.
# validate_plan re-executes the plan from scratch, from the initial state,
# without consulting anything the search recorded.


def validate_plan(problem, plan, states=None):
    """Re-execute `plan` from I and check every step.  Returns (ok, report)."""
    lines = []
    state = problem.initial
    lines.append("S0 = %s" % show_state(state))

    for i, action in enumerate(plan, start=1):
        if action not in problem.actions:
            return False, lines + ["step %d: %s is not an action of this problem"
                                   % (i, action.name)]
        if not action.applicable(state):
            return False, lines + ["step %d: %s NOT applicable -- %s"
                                   % (i, action.name,
                                      action.why_inapplicable(state))]
        lines.append("  a%d = %-20s pre ok: %s"
                     % (i, action.name, _pre_report(action, state)))
        state = action.apply(state)
        lines.append("S%d = %s" % (i, show_state(state)))
        if states is not None and state != states[i]:
            return False, lines + ["step %d: state disagrees with the state the "
                                   "planner recorded" % i]

    if not problem.satisfies_goal(state):
        return False, lines + ["final state does not entail the goal %s"
                               % show_state(problem.goal)]
    lines.append("final state |= G = %s   VALID" % show_state(problem.goal))
    return True, lines


def _pre_report(action, state):
    bits = []
    for p in sorted(action.pos_pre):
        bits.append("%s in S" % p)
    for p in sorted(action.neg_pre):
        bits.append("%s not in S" % p)
    return ("; ".join(bits)) if bits else "(none)"


# ----------------------------------------------------------------------------
# 6. The warehouse domain
# ----------------------------------------------------------------------------

LOCATIONS = ["A", "B", "C"]
CONNECTED = [("A", "B"), ("B", "A"), ("B", "C"), ("C", "B")]


def move_action(x, y):
    return Action(
        name="Move(%s,%s)" % (x, y),
        pos_pre=["At(Robot,%s)" % x],
        pos_eff=["At(Robot,%s)" % y],
        neg_eff=["At(Robot,%s)" % x],
    )


def pickup_action(x):
    return Action(
        name="PickUp(Package,%s)" % x,
        pos_pre=["At(Robot,%s)" % x, "At(Package,%s)" % x],
        neg_pre=["Holding(Package)"],          # [HAND] cannot pick up twice
        pos_eff=["Holding(Package)"],
        neg_eff=["At(Package,%s)" % x],
    )


def drop_action(x):
    return Action(
        name="Drop(Package,%s)" % x,
        pos_pre=["At(Robot,%s)" % x, "Holding(Package)"],
        pos_eff=["At(Package,%s)" % x],
        neg_eff=["Holding(Package)"],
    )


def warehouse(with_pickup=True, with_drop=True,
              connected_moves=True, name=None):
    """Build the warehouse problem.

    connected_moves=False instantiates Move over EVERY ordered pair of
    locations instead of only over connected ones.  That is the defect
    described in LAB_REPORT.md section 7, Defect 2 -- it is kept here
    deliberately so the tests and the Prolog verifier have something real
    to catch.
    """
    if connected_moves:
        pairs = CONNECTED
    else:
        pairs = list(permutations(LOCATIONS, 2))

    actions = [move_action(x, y) for (x, y) in pairs]
    if with_pickup:
        actions += [pickup_action(x) for x in LOCATIONS]
    if with_drop:
        actions += [drop_action(x) for x in LOCATIONS]

    if name is None:
        name = "warehouse"
        extras = []
        if not with_pickup:
            extras.append("no PickUp")
        if not with_drop:
            extras.append("no Drop")
        if not connected_moves:
            extras.append("unrestricted Move")
        if extras:
            name += " (" + ", ".join(extras) + ")"

    return Problem(
        initial=make_state("At(Robot,A)", "At(Package,A)"),
        actions=actions,
        goal=make_state("At(Package,C)"),
        name=name,
    )


# ----------------------------------------------------------------------------
# 7. Reporting
# ----------------------------------------------------------------------------


def report(problem, result, show_validation=True):
    out = []
    out.append("problem          : %s" % problem.name)
    out.append("initial state I  : %s" % show_state(problem.initial))
    out.append("goal G           : %s" % show_state(problem.goal))
    out.append("ground actions   : %d" % len(problem.actions))
    out.append("                   %s"
               % ", ".join(a.name for a in problem.actions))
    out.append("")

    applicable = problem.applicable_actions(problem.initial)
    out.append("applicable in I  : %s"
               % (", ".join(a.name for a in applicable) or "(none)"))
    for a in problem.actions:
        if a not in applicable:
            out.append("    blocked: %-22s %s"
                       % (a.name, a.why_inapplicable(problem.initial)))
    out.append("")

    out.append("plan found       : %s" % result.found)
    out.append("plan length      : %s" % result.length)
    out.append("states expanded  : %d" % result.expanded)
    out.append("states generated : %d" % result.generated)
    out.append("peak frontier    : %d" % result.peak_frontier)
    out.append("")

    if not result.found:
        out.append("No plan found.")
        return "\n".join(out)

    out.append("plan:")
    for i, a in enumerate(result.plan, start=1):
        out.append("  %d. %s" % (i, a.name))
    out.append("")
    out.append("state trajectory:")
    for i, s in enumerate(result.states):
        via = "" if i == 0 else "   via %s" % result.plan[i - 1].name
        out.append("  %-3s %s%s" % ("S%d" % i, show_state(s), via))

    if show_validation:
        out.append("")
        out.append("independent re-execution of the plan:")
        ok, lines = validate_plan(problem, result.plan, result.states)
        for line in lines:
            out.append("  " + line)
        out.append("  => %s" % ("PLAN VALID" if ok else "PLAN INVALID"))

    return "\n".join(out)


def main():
    problem = warehouse()
    print("=" * 78)
    print("Warehouse planning problem -- BFS planner")
    print("=" * 78)
    print(report(problem, bfs_plan(problem)))


if __name__ == "__main__":
    main()
